import type { HealthFunctionalFoodNutritionItem } from "./health-functional-food-nutrition-api";

export const healthFunctionalFoodNutritionSnapshot = {
  totalCount: 4380,
  fetchedAt: "2026-06-07T09:12:26.533Z",
  foods: [
    {
      foodCode: "F102-054540000-0037",
      name: "힐리 엠에스엠 770",
      typeName: "건강기능식품",
      originName: "건강기능식품",
      largeCategory: "기능성 원료",
      representativeFood: "엠에스엠",
      middleCategory: "엠에스엠",
      kind: "",
      servingUnit: "800mg",
      energy: "3",
      protein: "0.00",
      fat: "0.00",
      carbs: "0.50",
      sugars: "",
      fiber: "",
      calcium: "",
      iron: "",
      potassium: "",
      sodium: "0",
      vitaminA: "",
      vitaminC: "",
      vitaminD: "",
      saturatedFat: "",
      transFat: "",
      oneServing: "1정",
      oneServingWeight: "800mg",
      dailyIntakeCount: "2회",
      intakeTarget: "",
      reportNo: "22US32581G6",
      maker: "PIONITY HEALTH&BIO EXPERT GROUP",
      importer: "소울드림 주식회사",
      distributor: "해당없음",
      imported: "Y",
      originCountry: "미국",
      sourceName: "식품의약품안전처",
      createdAt: "2022-09-01",
      updatedAt: "2025-12-30"
    },
    {
      foodCode: "F101-020200000-0003",
      name: "힐리 셀레늄 300",
      typeName: "건강기능식품",
      originName: "건강기능식품",
      largeCategory: "영양성분",
      representativeFood: "셀레늄",
      middleCategory: "셀레늄",
      kind: "",
      servingUnit: "500mg",
      energy: "0",
      protein: "0.00",
      fat: "0.00",
      carbs: "0.00",
      sugars: "",
      fiber: "",
      calcium: "",
      iron: "",
      potassium: "",
      sodium: "0",
      vitaminA: "",
      vitaminC: "",
      vitaminD: "",
      saturatedFat: "",
      transFat: "",
      oneServing: "1캡슐",
      oneServingWeight: "500mg",
      dailyIntakeCount: "1회",
      intakeTarget: "",
      reportNo: "22US29839G8",
      maker: "PIONITY HEALTH&BIO EXPERT GROUP",
      importer: "소울드림 주식회사",
      distributor: "해당없음",
      imported: "Y",
      originCountry: "미국",
      sourceName: "식품의약품안전처",
      createdAt: "2022-07-18",
      updatedAt: "2025-12-30"
    },
    {
      foodCode: "F101-003030000-0144",
      name: "힐리 비타민D 5000",
      typeName: "건강기능식품",
      originName: "건강기능식품",
      largeCategory: "영양성분",
      representativeFood: "비타민 D",
      middleCategory: "비타민 D",
      kind: "",
      servingUnit: "250mg",
      energy: "0",
      protein: "0.00",
      fat: "0.00",
      carbs: "0.00",
      sugars: "",
      fiber: "",
      calcium: "",
      iron: "",
      potassium: "",
      sodium: "0",
      vitaminA: "",
      vitaminC: "",
      vitaminD: "",
      saturatedFat: "",
      transFat: "",
      oneServing: "1캡슐",
      oneServingWeight: "250mg",
      dailyIntakeCount: "1회",
      intakeTarget: "",
      reportNo: "22US34788G7",
      maker: "PIONITY HEALTH&BIO EXPERT GROUP",
      importer: "소울드림 주식회사",
      distributor: "해당없음",
      imported: "Y",
      originCountry: "미국",
      sourceName: "식품의약품안전처",
      createdAt: "2022-08-16",
      updatedAt: "2025-12-30"
    },
    {
      foodCode: "F101-016160000-0030",
      name: "힐리 마그네슘 500",
      typeName: "건강기능식품",
      originName: "건강기능식품",
      largeCategory: "영양성분",
      representativeFood: "마그네슘",
      middleCategory: "마그네슘",
      kind: "",
      servingUnit: "1300mg",
      energy: "4",
      protein: "0.00",
      fat: "0.00",
      carbs: "1.00",
      sugars: "",
      fiber: "",
      calcium: "",
      iron: "",
      potassium: "",
      sodium: "0",
      vitaminA: "",
      vitaminC: "",
      vitaminD: "",
      saturatedFat: "",
      transFat: "",
      oneServing: "1캡슐",
      oneServingWeight: "1300mg",
      dailyIntakeCount: "1회",
      intakeTarget: "",
      reportNo: "22US40569G0",
      maker: "PIONITY HEALTH&BIO EXPERT GROUP",
      importer: "소울드림 주식회사",
      distributor: "해당없음",
      imported: "Y",
      originCountry: "미국",
      sourceName: "식품의약품안전처",
      createdAt: "2022-09-20",
      updatedAt: "2025-12-30"
    },
    {
      foodCode: "F102-002020000-0017",
      name: "흑백면역",
      typeName: "건강기능식품",
      originName: "건강기능식품",
      largeCategory: "기능성 원료",
      representativeFood: "홍삼",
      middleCategory: "홍삼",
      kind: "",
      servingUnit: "15000mg",
      energy: "44",
      protein: "0.00",
      fat: "0.00",
      carbs: "11.00",
      sugars: "2.00",
      fiber: "",
      calcium: "",
      iron: "",
      potassium: "",
      sodium: "0",
      vitaminA: "",
      vitaminC: "",
      vitaminD: "",
      saturatedFat: "",
      transFat: "",
      oneServing: "1포",
      oneServingWeight: "15000mg",
      dailyIntakeCount: "1회",
      intakeTarget: "",
      reportNo: "23KR40263G3",
      maker: "GEUMSAN BLACK GINSENG CO., LTD.",
      importer: "성원피씨엠 주식회사",
      distributor: "해당없음",
      imported: "Y",
      originCountry: "대한민국",
      sourceName: "식품의약품안전처",
      createdAt: "2023-07-12",
      updatedAt: "2025-12-30"
    },
    {
      foodCode: "F103-001010000-2631",
      name: "휴덴케어 프리미엄",
      typeName: "건강기능식품",
      originName: "건강기능식품",
      largeCategory: "복합",
      representativeFood: "복합제품(영양소, 기능성)",
      middleCategory: "복합제품(영양소, 기능성)",
      kind: "",
      servingUnit: "1500mg",
      energy: "0",
      protein: "0.00",
      fat: "0.00",
      carbs: "0.00",
      sugars: "",
      fiber: "",
      calcium: "210",
      iron: "",
      potassium: "",
      sodium: "0",
      vitaminA: "",
      vitaminC: "50.00",
      vitaminD: "17.50",
      saturatedFat: "",
      transFat: "",
      oneServing: "1정",
      oneServingWeight: "1500mg",
      dailyIntakeCount: "1회",
      intakeTarget: "",
      reportNo: "22US37539G2",
      maker: "NATURALWELL INC",
      importer: "(주)더블유에이치글로벌",
      distributor: "해당없음",
      imported: "Y",
      originCountry: "미국",
      sourceName: "식품의약품안전처",
      createdAt: "2022-08-31",
      updatedAt: "2025-12-30"
    }
  ] satisfies HealthFunctionalFoodNutritionItem[]
};
